# Python Basics

- Learning: 2~3 students form a small group to run the scripts together.

- About Google Colab
  - How to use Google Colab?
  - https://www.youtube.com/watch?v=inN8seMm7UI
  - https://colab.research.google.com/#scrollTo=5fCEDCU_qrC0

- Section 1: Basic Python syntax
- Section 2: Loading data (Pandas)
- Section 3: Viewing data (Numpy and Pandas)

- Data: https://drive.google.com/file/d/1LTxyDrSZD2f0LuELMenGVkWeag7KebHP/view?usp=sharing
- Data dictionary: https://docs.google.com/spreadsheets/d/1juSpTKO07HnzxAKRTg5MLLj1SWR60tX3/edit?usp=sharing&ouid=115425849068992643587&rtpof=true&sd=true

For each section, I cannot cover everything. Please take the Practicum AI at UFL to learn more about python coding for AI.

**Link**: https://calendar.hr.ufl.edu/event/practicum-ai/all/

## 1. Basic Python Syntax

In [2]:
# print
# anything after a hashtag is a comment
print("Hello world") # round bracket

Hello world


### 1.1 Basic data types

In [3]:
# booleans
x = True # or false
type(x)

bool

In [4]:
# integers (discrete values)
x = 1
type(x)

int

In [5]:
# floating-point numbers (continuous values)
x = 100.5
type(x)

float

In [6]:
# strings - quotation marks for strings
x = 'Gainesville'
type(x)

str

In [7]:
# list of items
x = [1, 2, 3, 'Gainesville'] # square bracket
type(x)

list

In [8]:
# sets
x = {1, 2, 3, 3, 2} # curly bracket
type(x)

set

In [9]:
# tuple
x = (12, "Artificial intellignece and built environment")
type(x)

tuple

In [10]:
# dictionary
x = {"first name": "Shenhao", "last name": "Wang", "lab": "Urban AI"}
type(x)

dict

In [11]:
# keys and values in a dictionary
x = {"first name": "Shenhao", "last name": "Wang", "lab": "Urban AI"}
print(x.keys())
print(x.values())

dict_keys(['first name', 'last name', 'lab'])
dict_values(['Shenhao', 'Wang', 'Urban AI'])


## **Exercise.** Create a dictionary, in which you include "first name" and "last name" as keys, and put your names there as values. Print them out.

In [12]:
x = {"first name": "Bryce", "last name": "Bass"}
print(x.values())

dict_values(['Bryce', 'Bass'])


### 1.2 Basic algebraic operations

In [13]:
# adding integers
x = 1 + 2
print(type(x))
print(x)

<class 'int'>
3


In [14]:
# adding floats
x = 1.5 + 2.5
print(type(x))
print(x)

<class 'float'>
4.0


In [15]:
# multiplication
x = 3 * 4
print(x)

12


In [16]:
# division
x = 3/4 # slash symbol
print(x)

0.75


In [17]:
# exponential operation
x = 2 ** 3
print(x)

8


In [18]:
# order of basic algebraic operations
x = 2 * 3 ** 2
print(x)

18


## **Exercise.** Assigning 5.0 and 3.0 to x and y. Then compute the value of x divided by y.

In [19]:
x = 5.0
y = 3.0
print(x / y)

1.6666666666666667


### 1.3 Boolean operations

In [20]:
# check equality
x = 10 # assign value using one equal sign
x == 10 # check equality using two equal signs

True

In [21]:
# check larger than
x = 10
x > 100

False

In [22]:
# True/False; and/or/not
x = True
y = False

In [23]:
x and y

False

In [24]:
x or y

True

In [25]:
not x

False

In [26]:
x and not y

True

## **Exercise.** Assign value 13 to variable x. Generate the boolean output whether x is larger than 10.

In [27]:
x = 13
x > 10

True

### 1.4 String operations

In [28]:
x = "Hello" + "World"
print(x)

HelloWorld


In [29]:
x[0]

'H'

In [30]:
x[2]

'l'

In [31]:
# You cannot add string and float/int types
x + 1.0

TypeError: can only concatenate str (not "float") to str

In [32]:
# but you can multiply them
x * 2

'HelloWorldHelloWorld'

### 1.5 If condition: if, elif, else;

In [35]:
# basic syntax 1
# pay attention to small symbols: space, colon & indent
condition = False
if condition:
  print("See me when the condition is true")
else:
  print("wrong")

wrong


In [36]:
# example
z = 4
if z - 2 == 2:
  print("z is four")

z is four


In [37]:
# basic syntax 2
condition = True
if condition:
  print("See me when the condition is true.")
else:
  print("See me when the condition is false.")

See me when the condition is true.


In [38]:
# example
z = 5
if z%2 == 0: # remainder is zero
  print("z is even")
else: # remainder is one
  print("z is odd")

z is odd


In [39]:
# basic syntax 3: if-elif-else
# example
z = 3
if z%2 == 0:
  print("z is divisible by 2") # False
elif z%3 == 0:
  print("z is divisible by 3") # True
else:
  print("z is neither divisible by 2 nor by 3")

z is divisible by 3


## **Exercise.** Assign 10 to x. If x is bigger than 0, print "x is a positive number".

In [40]:
x = 10
if x > 0:
  print("x is a positive number")
else:
  print("X is a negative number")


x is a positive number


### 1.6 For Loop

In [41]:
# example 1
# print every string
x = "Hello World"
for letter in x:
  print(letter)

H
e
l
l
o
 
W
o
r
l
d


In [42]:
# example 2
# adding values
initial_value = 0
for i in range(0,4): # range(4): 0, 1, 2, 3
  initial_value = initial_value + i
  print(initial_value)

0
1
3
6


In [43]:
# example 3
# print the list
my_list = ['Orlando', 'Gainesville', 'Miami', 'Tampa Bay', 'Jacksonville']
for item in my_list:
  print(item)

Orlando
Gainesville
Miami
Tampa Bay
Jacksonville


## **Exercise.** Calcluate the sum of all numbers from 1 to 100.

In [44]:
sum = 0
for i in range(0, 101):
    sum = sum + i
print(sum)

5050


### 1.7 Functions

In [45]:
# example 1.
def add_one(x):
  '''
  Add one to the value x  #Just comments here.
  '''
  y = x + 1
  return y

# test
x = 5
y = add_one(x)
print(y)

6


## **Exercise.** Develop a function called multiply_two, which can multiply the input value by two as the output. Then test this function with an example.

In [46]:
def multiply_two(x):
    y = x * 2
    return y
x = 10
y = multiply_two(x)
print(y)

20


## 2. Loading data

- Please create a folder named as data under your Colab Notebooks folder. Then copy and paste the data set (Florida_ct.csv) and the documentation under the data folder.

In [47]:
# import pandas
import pandas as pd

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [51]:
# load the csv file using pandas
df = pd.read_csv('SampleDataset/Florida_ct.csv', index_col = 0)

In [52]:
# check the dataframe
df

pop_total  sex_total  sex_male  sex_female  age_median  households  \
0        2812.0     2812.0    1383.0      1429.0        39.4       931.0   
1        4709.0     4709.0    2272.0      2437.0        34.2      1668.0   
2        5005.0     5005.0    2444.0      2561.0        34.1      1379.0   
3        6754.0     6754.0    2934.0      3820.0        31.3      2238.0   
4        3021.0     3021.0    1695.0      1326.0        44.1      1364.0   
...         ...        ...       ...         ...         ...         ...   
4162    15742.0    15742.0    7957.0      7785.0        41.0      5517.0   
4163     5723.0     5723.0    2914.0      2809.0        43.0      2001.0   
4164    10342.0    10342.0    4657.0      5685.0        37.6      3746.0   
4165     8960.0     8960.0    4166.0      4794.0        37.2      3324.0   
4166     5083.0     5083.0    2573.0      2510.0        39.2      1755.0   

      race_total  race_white  race_black  race_native  ...  travel_walk_ratio  \
0         2812.0      2086.0       517.0          0.0  ...           0.014815   
1         4709.0      2382.0      1953.0          0.0  ...           0.022150   
2         5005.0      2334.0      2206.0        224.0  ...           0.026141   
3         6754.0      4052.0      1671.0        326.0  ...           0.052697   
4         3021.0      2861.0       121.0          0.0  ...           0.003014   
...          ...         ...         ...          ...  ...                ...   
4162     15742.0     13894.0      1128.0         64.0  ...           0.000000   
4163      5723.0      4664.0       482.0          0.0  ...           0.017050   
4164     10342.0      7956.0      1351.0         13.0  ...           0.000000   
4165      8960.0      6286.0      1831.0          0.0  ...           0.024021   
4166      5083.0      3753.0       987.0          0.0  ...           0.045983   

      travel_work_home_ratio  edu_bachelor_ratio  edu_master_ratio  \
0                   0.024242            0.183838          0.029798   
1                   0.004615            0.135222          0.040245   
2                   0.027913            0.213247          0.064620   
3                   0.004054            0.093379          0.082510   
4                   0.013059            0.219868          0.138631   
...                      ...                 ...               ...   
4162                0.062212            0.164241          0.084891   
4163                0.047581            0.215161          0.084563   
4164                0.038862            0.137002          0.030591   
4165                0.064132            0.174399          0.063014   
4166                0.046488            0.113451          0.022466   

      edu_phd_ratio  edu_higher_edu_ratio  employment_unemployed_ratio  \
0          0.003030              0.216667                     0.286635   
1          0.003220              0.178686                     0.318327   
2          0.007431              0.285299                     0.366755   
3          0.012599              0.188488                     0.314452   
4          0.007064              0.365563                     0.218447   
...             ...                   ...                          ...   
4162       0.002066              0.251197                     0.401551   
4163       0.007005              0.306730                     0.411036   
4164       0.002049              0.169643                     0.353295   
4165       0.003126              0.240540                     0.363482   
4166       0.002247              0.138163                     0.491815   

      vehicle_per_capita  vehicle_per_household  vacancy_ratio  
0               0.528094               1.595059       0.155938  
1               0.460183               1.299161       0.152869  
2               0.450949               1.636693       0.162211  
3               0.474830               1.432976       0.178716  
4               0.659053               1.459677       0.335930  


This is the data set from US Census. Each row represents a census tract, and each column represents a variable. We could check the columns one by one using numpy and pandas. Further details of the variables can be found in the documentation csv file.

## **Exercise.** Everyone could load and check this dataframe.

## 3. Viewing data

- Numpy and pandas are the two most common Python packages to process data and describe the summary statistics for data sets.

### 3.1 Data types in numpy and pandas

Before delving into the data set, let's be familiar with the data structures in numpy and pandas.

In [53]:
# import numpy package
# Note: numpy for matrix operation; pandas for data sets.
import numpy as np
import pandas as pd

In [54]:
# Numpy array (1D)
array_1 = np.arange(0,5)
array_1

array([0, 1, 2, 3, 4])

In [55]:
# Numpy array (2D)
# 1. Two printings
# 2. random.randint - randomly generating 20 different values between 1 and 2.
# 3. reshape: reshaping the array to a matrix with 5*4 shape.
array_1D = np.random.randint(1,10,20)
print(array_1D)
array_2D = array_1D.reshape(5, -1)
print(array_2D)

[6 8 4 3 4 1 2 8 9 5 4 6 4 5 1 8 1 4 4 2]
[[6 8 4 3]
 [4 1 2 8]
 [9 5 4 6]
 [4 5 1 8]
 [1 4 4 2]]


In [56]:
# Pandas series
my_list = [8, 5, 77, 2]
my_series = pd.Series(my_list)
my_series

0     8
1     5
2    77
3     2
dtype: int64

In [57]:
# Pandas dataframe
# a dict can contain multiple lists and label them
my_dict = {'hh_income'  : [71000, 28000, 35000, 120000],
           'home_value' : [520000, 275000, 400000, 980000]}
my_dict

{'hh_income': [71000, 28000, 35000, 120000],
 'home_value': [520000, 275000, 400000, 980000]}

## **Exercise.** Create a one-dimensional numpy array including ten one's. (Google: numpy.ones)
## **Exercise.** Create a two-dimensional numpy arrays including 3*3 one's. (Google: numpy.ones)
## **Exercise.** Create a pandas dataframe with two columns and three rows. The first column is: 'name': ['Bob', 'Sue', 'Mary']; the second column is 'age': [39, 57, 28].

### 3.2 Viewing the loaded Data

In [58]:
# shape
df.shape

(4167, 88)

In [59]:
# view the head
df.head()

pop_total  sex_total  sex_male  sex_female  age_median  households  \
0     2812.0     2812.0    1383.0      1429.0        39.4       931.0   
1     4709.0     4709.0    2272.0      2437.0        34.2      1668.0   
2     5005.0     5005.0    2444.0      2561.0        34.1      1379.0   
3     6754.0     6754.0    2934.0      3820.0        31.3      2238.0   
4     3021.0     3021.0    1695.0      1326.0        44.1      1364.0   

   race_total  race_white  race_black  race_native  ...  travel_walk_ratio  \
0      2812.0      2086.0       517.0          0.0  ...           0.014815   
1      4709.0      2382.0      1953.0          0.0  ...           0.022150   
2      5005.0      2334.0      2206.0        224.0  ...           0.026141   
3      6754.0      4052.0      1671.0        326.0  ...           0.052697   
4      3021.0      2861.0       121.0          0.0  ...           0.003014   

   travel_work_home_ratio  edu_bachelor_ratio  edu_master_ratio  \
0                0.024242            0.183838          0.029798   
1                0.004615            0.135222          0.040245   
2                0.027913            0.213247          0.064620   
3                0.004054            0.093379          0.082510   
4                0.013059            0.219868          0.138631   

   edu_phd_ratio  edu_higher_edu_ratio  employment_unemployed_ratio  \
0       0.003030              0.216667                     0.286635   
1       0.003220              0.178686                     0.318327   
2       0.007431              0.285299                     0.366755   
3       0.012599              0.188488                     0.314452   
4       0.007064              0.365563                     0.218447   

   vehicle_per_capita  vehicle_per_household  vacancy_ratio  
0            0.528094               1.595059       0.155938  
1            0.460183               1.299161       0.152869  
2            0.450949               1.636693       0.162211  
3            0.474830               1.432976       0.178716  
4            0.659053               1.459677       0.335930  

[5 rows x 88 columns]

In [60]:
# view the tail
df.tail(2)

pop_total  sex_total  sex_male  sex_female  age_median  households  \
4165     8960.0     8960.0    4166.0      4794.0        37.2      3324.0   
4166     5083.0     5083.0    2573.0      2510.0        39.2      1755.0   

      race_total  race_white  race_black  race_native  ...  travel_walk_ratio  \
4165      8960.0      6286.0      1831.0          0.0  ...           0.024021   
4166      5083.0      3753.0       987.0          0.0  ...           0.045983   

      travel_work_home_ratio  edu_bachelor_ratio  edu_master_ratio  \
4165                0.064132            0.174399          0.063014   
4166                0.046488            0.113451          0.022466   

      edu_phd_ratio  edu_higher_edu_ratio  employment_unemployed_ratio  \
4165       0.003126              0.240540                     0.363482   
4166       0.002247              0.138163                     0.491815   

      vehicle_per_capita  vehicle_per_household  vacancy_ratio  
4165            0.478571               1.290012       0.017440  
4166            0.389337               1.127635       0.129464  

[2 rows x 88 columns]

In [61]:
# check the column names
df.columns

Index(['pop_total', 'sex_total', 'sex_male', 'sex_female', 'age_median',
       'households', 'race_total', 'race_white', 'race_black', 'race_native',
       'race_asian', 'inc_total_pop', 'inc_no_pop', 'inc_with_pop',
       'inc_pop_10k', 'inc_pop_1k_15k', 'inc_pop_15k_25k', 'inc_pop_25k_35k',
       'inc_pop_35k_50k', 'inc_pop_50k_65k', 'inc_pop_65k_75k', 'inc_pop_75k',
       'inc_median_ind', 'travel_total_to_work', 'travel_driving_to_work',
       'travel_pt_to_work', 'travel_taxi_to_work', 'travel_cycle_to_work',
       'travel_walk_to_work', 'travel_work_from_home', 'edu_total_pop',
       'bachelor_male_25_34', 'master_phd_male_25_34', 'bachelor_male_35_44',
       'master_phd_male_35_44', 'bachelor_male_45_64', 'master_phd_male_45_64',
       'bachelor_male_65_over', 'master_phd_male_65_over',
       'bachelor_female_25_34', 'master_phd_female_25_34',
       'bachelor_female_35_44', 'master_phd_female_35_44',
       'bachelor_female_45_64', 'master_phd_female_45_64',
       '